syntax = "proto3";

package pulsoats.live.v1;

import "core/v1/detect.proto";
import "core/v1/market.proto";
import "core/v1/run.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/pulsoats/contracts/gen/go/live/v1;livepb";

message Run {
  core.v1.BaseRun base_run = 1;
  int64 sum_profit_ppm = 2;
  int64 avg_profit_ppm = 3;
  optional google.protobuf.Timestamp finished_at = 4;
  optional string finished_by = 5;
}

message NewRunRequest {
  pulsoats.core.v1.MarketSpec market = 1;
  string interval = 2;
  pulsoats.core.v1.DetectorConfig detector_config = 3;
  repeated pulsoats.core.v1.FilterConfig filters_configs = 4;
}

message ListRunsFilter {
  repeated string categories = 1;
  repeated string symbols = 2;
  repeated string intervals = 3;
  repeated string detector_codes = 4;
  repeated int32 statuses = 5;

  optional int64 min_signals = 6;
  optional int64 max_signals = 7;

  optional google.protobuf.Timestamp created_from = 8;
  optional google.protobuf.Timestamp created_to = 9;
}

message ListRunsPagedRequest {
  int32 limit = 1;
  optional string before_id = 2;
  bool order_dir_asc = 3;
  optional ListRunsFilter filter = 4;
}

message ListRunsPagedResponse {
  repeated Run runs = 1;
  bool has_more = 2;
  optional string next_before_id = 3;
}

message Signal {
  string id = 1;
  string run_id = 2;
  pulsoats.core.v1.MarketSpec market = 3;
  string interval = 4;
  string detector_code = 5;
  string detector_version = 6;
  google.protobuf.Timestamp candle_time = 7;
  int64 buy_value = 8;
  int64 take_profit_value = 9;
  int64 stop_loss_value = 10;
  int64 expected_return_ppm = 11;
  google.protobuf.Timestamp created_at = 12;
}

message ListSignalsFilter {
  optional string run_id = 1;
  repeated string categories = 2;
  repeated string symbols = 3;
  repeated string intervals = 4;
  repeated string detectors_codes = 5;
  optional google.protobuf.Timestamp created_from = 6;
  optional google.protobuf.Timestamp created_to = 7;
}

message ListSignalsPagedRequest {
  int32 limit = 1;
  optional string before_id = 2;
  bool order_dir_asc = 3;
  optional ListSignalsFilter filter = 4;
}

message ListSignalsPagedResponse {
  repeated Signal signals = 1;
  bool has_more = 2;
  optional string next_before_id = 3;
}

message Event {
  string run_id = 1;
  oneof payload {
    Run run = 2;
    Signal signal = 3;
  }
}

message WorkerStats {
  int32 runs_total = 1;
  int64 signals_total = 2;
}

service Live {
  rpc NewRun(NewRunRequest) returns (Run); // x-user-id METADATA IS REQUIRED
  rpc StopRun(core.v1.RunID) returns (google.protobuf.Empty); // x-user-id METADATA IS REQUIRED
  rpc StopAll(google.protobuf.Empty) returns (google.protobuf.Empty); // x-user-id METADATA IS REQUIRED
  rpc RestartRun(core.v1.RunID) returns (Run); // x-user-id METADATA IS REQUIRED
  rpc GetRun(core.v1.RunID) returns (Run);

  rpc StreamWorkerStats(google.protobuf.Empty) returns (stream WorkerStats);
  rpc StreamEvents(google.protobuf.Empty) returns (stream Event);

  rpc ListRunsPaged(ListRunsPagedRequest) returns (ListRunsPagedResponse);
  rpc ListSignalsPaged(ListSignalsPagedRequest) returns (ListSignalsPagedResponse);
}