syntax = "proto3";

package pulsoats.core.v1;

import "google/protobuf/empty.proto";

option go_package = "github.com/pulsoats/contracts/gen/go/core/v1;corepb";

message DetectorConfig {
  string code = 1;
  string version = 2;
  string opts_label = 3;
  bytes opts = 4;
}

message DetectorMeta {
  string code = 1;
  string version = 2;
  string description = 3;
  bytes opts_schema = 4;
}

message FilterConfig {
  string code = 1;
  int32 period = 2;
}

message FilterMeta {
  string code = 1;
  string description = 2;
}